export const siteConfig = {
  name: "Minchan Kim - Aspiring AI & Aerospace Engineer",
  authorName: "Minchan Kim",
  username: "MINBBBB1201",
  description:
    "Minchan Kim - High school student building at the intersection of software engineering and aerospace, from flight-booking web apps to rocket propulsion test stands. Explore my projects, experience, and contributions.",
  url: "https://TODO_YOUR_DOMAIN.com",
  links: {
    linkedin: "https://www.linkedin.com/in/minchan-kim-6490313ba/",
    github: "https://github.com/MINBBBB1201",
    templateRepo: "https://github.com/COSMOS-Aero-Engineering/Rocket-Thrust-Test-Stand",
  },
  ogImage: "",
  iconIco: "",
  logoIcon: "",
  keywords: [
    "Minchan Kim",
    "AI Engineer",
    "Aerospace Engineering",
    "Software Engineer",
    "Full Stack Developer",
    "Next.js Developer",
    "TypeScript",
    "Python Developer",
    "React Three Fiber",
    "Rocket Propulsion",
    "Aerodynamics",
    "Robotics",
    "Qingdao Daewon International School",
    "Student Portfolio",
    "AI Engineering",
  ],
};
